### ISSUE TITLE
No loader is configured for ".png" files:

### ISSUE THREAD

**Issue by vdjurdjevic** [fedeya/remix-sitemap#18]
**Describe the bug**
I get No loader is configured for ".png" files: error when trying to run next-sitemap command after build.  I have static asset import all over the app.

**To Reproduce**
Import static asset into any route
Run remix build
Run remix-sitemap

**Expected behavior**
Sitemap is generated

**Screenshots**
![image](https://user-images.githubusercontent.com/17208031/229160377-925665c2-3c99-4006-92cc-bae228f5d7a2.png)
![image](https://user-images.githubusercontent.com/17208031/229160465-35eba96d-d426-459f-ae82-92e0dda6306a.png)

**Desktop (please complete the following information):**
 - OS: MacOs Ventura

**Comment by fedeya** [comment]
Hi @vdjurdjevic! thanks, this should be fixed in [v1.3.2](https://github.com/fedeya/remix-sitemap/releases/tag/v1.3.2)
