### ISSUE TITLE
Better support for V2 routing conventions

### ISSUE THREAD

**Issue by isaac-jordan** [fedeya/remix-sitemap#32]
**Describe the bug**
Hi there, thanks for this great library. Really simplifies sitemaps.

I've just opted in to V2 routing conventions in my Remix project, and I have a `blog.$slug.tsx` route and ` blog._index.tsx` route. Unfortunately remix-sitemap doesn't seem to pick up the index page for the blog automatically (`/blog`), but adding the following code made it start working correctly:

```
export const sitemap: SitemapFunction = async ({ config, request }) => {    
    return [
        {loc: "/blog"},
    ];
};
```

**Expected behavior**
Ideally it would just pick up this route automatically, like other routes.

**Comment by fedeya** [comment]
Hi @isaac-jordan thanks!

I released a new version today to fix this, could you try again with the latest version?

**Comment by isaac-jordan** [comment]
Looks good @fedeya, thanks!
