### ISSUE TITLE
Cloudflare pages support

### ISSUE THREAD

**Issue by Mihai-github** [fedeya/remix-sitemap#38]
Hello, 

I'm in the process of developing a Remix.js application intended for deployment on Cloudflare Pages. I'm interested in confirming whether this library is compatible with the deployment platform. As of now, I'm attempting to display the request output upon refreshing the page, but I'm encountering a lack of results. I'm uncertain if this issue stems from a mistake on my end or if there's another underlying reason for this behavior.

`
export const sitemap: SitemapFunction = async ({ config, request }) => {
    console.log({ request });
}
`

**Comment by fedeya** [comment]
This library should work with cloudflare pages, the error in the code is because you need to return an object with the required properties defined in the return type of `SitemapFunction`
