### ISSUE TITLE
Duplicate siteUrls in the xml

### ISSUE THREAD

**Issue by BryceBlankinship** [fedeya/remix-sitemap#41]
In my xml there are duplicate siteUrls:

`
<url>
<loc>https://example.com/</loc>
<lastmod>2023-08-27T23:12:21.058Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>
</url>
`
`
<url>
<loc>https://example.com/</loc>
<lastmod>2023-08-27T23:12:21.058Z</lastmod>
<changefreq>daily</changefreq>
<priority>0.7</priority>
</url>
`

Any idea? This may be another thing related to the v2 entry.server.js being different that I described in another issue.

**Comment by fedeya** [comment]
Sorry i can't reproduce this, can you provide more context with a repo? Thanks

**Comment by fedeya** [comment]
closed due to inactivity
