### ISSUE TITLE
Unable to set `news:publication_date`

### ISSUE THREAD

**Issue by AjaniBilby** [fedeya/remix-sitemap#52]
I'm using the following code to generate my [sitemap data](https://signplanet.net/sitemap-0.xml) for a particular dynamic route:
```tsx
export async function sitemap () {
	const data = await prisma.news.findMany({
		where: {
			isDraft: false
		},
		orderBy: [
			{ createdAt: "desc" }
		]
	});

	return data.map(entry => ({
		lastmod: entry.updatedAt.toISOString().split('T')[0],
		loc: `/news/${entry.id}`,
		news: [{
			title: entry.title,
			publication: {
				name: 'Signplanet',
				language: 'en'
			},
			publication_date: entry.publishAt.toISOString().split('T')[0]
		}]
	}))
};
```
Which then generates xml elements like:
```xml
<url>
	<loc>https://beta.signplanet.net/news/cllygso7r0001fju4xejanrra</loc>
	<lastmod>2023-09-01</lastmod>
	<changefreq>daily</changefreq>
	<priority>0.7</priority>
	<news:news>
		<news:publication>
			<news:name>Signplanet</news:name>
			<news:language>en</news:language>
		</news:publication>
		<news:title>Welcome to the new SignPlanet.net site</news:title>
	</news:news>
</url>
```

The fact that `publication_date` is missing when it's a [required field](https://developers.google.com/search/docs/crawling-indexing/sitemaps/news-sitemap#news-sitemap-reference) is quite a problem

**Comment by fedeya** [comment]
The publication_date is just `date` field in news object.

ex:
```ts
{
  title: entry.title,
  publication: { ... },
  date: entry.publishAt.toISOString()
}
```

**Comment by fedeya** [comment]
also using the `SitemapFunction` type you get autocomplete and type checking.

ex:
```ts
import type { SitemapFunction } from 'remix-sitemap';

export const sitemap: SitemapFunction = () => {}
```

**Comment by AjaniBilby** [comment]
`publication_date` -> `date`, was an unexpected transformation 😅

I'm used to swapping const functions to function functions because of the performance difference when they first started becoming popular... I should probably get out of that old habbit
